### ISSUE TITLE
Missing proto file error

### ISSUE THREAD

**Issue by congruentsquare** [alexeyxo/protobuf-swift-realm-compiler#3]
When I try to compile the protofile it give me a `Missing input file.` error. I tried the relative path, the absolute path, and changed the directory. Here's the exact command:

`protoc -I ./gtfs-realtime.proto --swift_realm_out="./"`

**Comment by alexeyxo** [comment]
We were updated [How to use](https://github.com/alexeyxo/protobuf-swift-realm-compiler#how-to-use).
