### ISSUE TITLE
Don't have a proto descriptor file

### ISSUE THREAD

**Issue by congruentsquare** [alexeyxo/protobuf-swift-realm-compiler#5]
Hi,

I am trying to generate a proto for a [gtfs realtime](https://developers.google.com/transit/gtfs-realtime/gtfs-realtime.proto) feed and it does not provide a descriptor file. How would I go about compiling the gtfs proto without a descriptor file?

**Comment by evdeve** [comment]
https://github.com/alexeyxo/protobuf-swift-realm-compiler#required-protocol-buffers-for-swift

**Comment by congruentsquare** [comment]
No they're not. I am able to compile a swift protobuf without a descriptor file.
